---
title: "Final for Env S 193DS"
format: html
---

# Set Up
```{r}
library(tidyverse) #loading in tidyverse
library(here) #loading in here
library(janitor) #loading in janitor
library(readxl) #loading in readxl
library(ggeffects) #loading in ggeffects
library(knitr) #loading in knitr
kelp <- read_csv(
  here(
    "Data", 
    "kelp.csv"
  ))
mopl <- read_csv(
  here(
    "Data", 
    "MOPL_nest-site_selection_Duchardt_et_al._2019.csv"
  )
)
```

# Problem 1. San Joaquin River Delta

## a. We determined that there is not enough evidence to suggest a difference between the median flooded wetland area across water year classification (wet, above normal, below normal, dry, critical drought). 

## b. A boxplot could be created to highlight the medians and interquartile ranges of the median flooded wetland area across the different water year classifications. On the x-axis would be the different water year classifications and on the y-axis would be the recorded flooded wetland area, including the medians. In addition to the boxplot, the points could be jittered vertically to further show the data. 

## c. 

## d. 

# Problem 2. Data Visualization

## a. 

## b. 

## c. 

## d. 

# Problem 3. Data Analysis 

## a. 

## b. 

## c. 

## d. 

## e. 

## f. 

## g. 

## h. 

## i. 

## j. 

# Problem 4. Affective and Exploratory Visualizations

## a. 

## b. 

## c. 

## d. 

## e. 

## f. 

## g. 

